#version: "3.10"
#
#services:
#  postgres:
#    image: postgres
##    env_file:
##      - .env
#    environment:
#      - POSTGRES_PASSWORD=test
#      - POSTGRES_USER=test
#      - POSTGRES_DB=test
##    volumes:
##      - ./docker/postgres:/var/lib/postgresql/data
##    command: -p 1221
##    expose:
##      - 1221
#    ports:
#      - 5433:5432
##    networks:
##      - default
#    restart: always
#
#  app:
#    build:
#      context: .
##    env_file:
##      - .env
#    volumes:
#      - ./:/app
##    working_dir: /app/src
##    command: uvicorn main:app --host 127.0.0.1 --port 80 --reload
#    depends_on:
#      - postgres
#    environment:
##      - DATABASE_URL=postgresql+asyncpg://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}
#      - DATABASE_URL=postgresql://test:test@postgres:5433/test
##    networks:
##      - default
#    ports:
#      - 8000:80
#
##networks:
##  default:
##    driver: bridge

version: '3.8'

services:
  app:
    build: .
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;'
    #command: bash -c 'cd .. && alembic upgrade head'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db
  db:
    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - WAIT_HOSTS=postgres:5432

#volumes:
#  postgres_data: