"""Role not uniq anymore

Revision ID: bbe9c48d3011
Revises: 6ddd7affe5c4
Create Date: 2023-12-20 21:25:09.347892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe9c48d3011'
down_revision: Union[str, None] = '6ddd7affe5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_role_key', 'users', ['role'])
    # ### end Alembic commands ###
